### ISSUE TITLE
Plotting Hazards

### ISSUE THREAD

**Issue by karpat90** [RobinDenz1/adjustedCurves#10]
Thank you for creating a great package! 

I wanted to ask if it is possible to plot hazards instead of survival curves?

Thank you for your help!

**Comment by RobinDenz1** [comment]
Thank you for the kind words.

Plotting hazards is currently not supported. I actually don't know if that is even possible for the methods used in this package. If you have any publications on the topic of confounder-adjusted hazards I would be very interested.
