### ISSUE TITLE
ggplot2 warning: Ignoring unknown parameters: linewidth

### ISSUE THREAD

**Issue by rix133** [RobinDenz1/adjustedCurves#13]
The plotting  sometimes  generates a warning that comes likely from the fact that an underling ggplot2 function has removed the linewith parameter  in the latest version.

**Comment by RobinDenz1** [comment]
Thank you for telling me about this. Could you perhaps provide a reproducible example to show me when this happens?
The `linewidth` parameter is the new version of the `size` parameter for most `ggplot2` syntax. So maybe updating `ggplot2` will fix your issue.

**Comment by RobinDenz1** [comment]
Yes this is an issue of your `ggplot2` version. The `size` parameter was deprecated in version `3.4`, you have `3.3.6`. Updating it will fix the warning.
