### ISSUE TITLE
How to change the interval of x-axis?

### ISSUE THREAD

**Issue by hhchang0210** [RobinDenz1/adjustedCurves#15]
Hi,

Is it possible to change the interval of x-axis?

Thank you.

**Comment by RobinDenz1** [comment]
The output of the `plot.adjustedsurv` function is a standard `ggplot2` object, meaning that you can change it (spacing, colors, axis, ...) in the same way you would change any other `ggplot2` object.

If you want to change the x-axis limits spacing you may use the `scale_x_continuous` function from the `ggplot2` package. A small example:

```R
library(adjustedCurves)
library(ggplot2)
library(survival)

data <- sim_confounded_surv()
data$group <- as.factor(data$group)

cox_mod <- coxph(Surv(time, event) ~ group + x1 + x2 + x4 + x5,
                 data=data, x=TRUE)

adjsurv <- adjustedsurv(data=data,
                        variable="group",
                        ev_time="time",
                        event="event",
                        method="direct",
                        outcome_model=cox_mod)

plot(adjsurv) +
  scale_x_continuous(breaks=seq(0, 2, 0.2))
```

Best wishes,
Robin
