### ISSUE TITLE
Apply to add a risk table

### ISSUE THREAD

**Issue by yijinbandouya** [RobinDenz1/adjustedCurves#18]
Hello, thank you very much for your preliminary work. We have a problem when using this package, it seems that this package cannot add risk table, can we request to add this function?

**Comment by RobinDenz1** [comment]
Unfortunately there is not much I can do. See #14 for an explanation.

**Comment by RobinDenz1** [comment]
Just wanted to let you know that there is now limited support for risk tables. Also relevant fot #14, and #16
