### ISSUE TITLE
Error in intermediary step, and extracting weighted dataset

### ISSUE THREAD

**Issue by Madhav1812** [RobinDenz1/adjustedCurves#21]
Hello,

Thank you for creating this package, it has been immensely helpful!

I have been running the adjustedcurves package for a specific dataset. When running the outcome model and the treatment model separately, there does not seem to be any issues. However, when I try to run the AIPTW model combining both the outcome and treatment model, I encounter the following error:

_Error in table(object$data[[all.vars(formula(object))[1]]], object$y) : 
  all arguments must have the same length_

I was not able to find the specific source of the error and I was unsure how to go about debugging this. Any help would be appreciated.

Additionally, I wanted to know if it would be possible to extract the weighted dataset when applying the treatment model to adjust the survival curve. 

Thank you

**Comment by RobinDenz1** [comment]
Thank you for the kind words.

Could you perhaps provide a reproducible example of your issue? Without seeing what you were doing it's impossible to say what the problem might be. If I had to guess I would say that you are providing something that isn't a `glm` object to the `treatment_model` argument.

When using the AIPTW method there is no "weighted dataset". The equation simply combines the propensity score estimates and the conditional survival probability predictions into a single estimate. The only method that actually uses a "weighted dataset" is `method="iptw_km"`, which includes a set of weighted numbers at risk in the output object.

**Comment by Madhav1812** [comment]
Hello,

Thank you for your response. I unfortunately cannot share the specific dataset I was using. but I can share the code skeleton that leads to this error.

`outcome_model <- survival::coxph(Surv(time = SURV_TIME_90, event = Mort_90_Init) ~ acute_mi + history_mi + chf + pvd + cvd + copd + dementia + paralysis + diabetes + diabetes_comp + renal_disease + liver_disease + ulcers + rheum_disease + aids + year + race + sex + age + LOS_DAY_CNT + Benzo_7_Init, data=table1new, x=TRUE)`

`treatment_model <- glm(Benzo_7_Init ~ acute_mi + history_mi + chf + pvd + cvd + copd + dementia + paralysis + diabetes + diabetes_comp + renal_disease + liver_disease + ulcers + rheum_disease + aids + year + race + sex + age + LOS_DAY_CNT,
                       data=table1new, family="binomial"(link="logit"))`

`adjsurv <- adjustedsurv(data=table1new,
                        variable="Benzo_7_Init",
                        ev_time="SURV_TIME_90",
                        event="Mort_90_Init",
                        method="aiptw",
                        treatment_model=treatment_model,
                        outcome_model=outcome_model,
                        conf_int=TRUE)`

Here the outcome regression adjusted curves and the IPTW curves seem to be working, but the issue arises when the two are combined. I'm not exactly sure how to show more of the dataset, but if you have any diagnostic methods that would be helpful.

For the weights, I realized that I was looking in the treatment model variable instead of the adjustedsurv variable. Thank you!

**Comment by RobinDenz1** [comment]
Your code looks fine to me. I understand that you cannot share the original data, but without a reproducible example I am unable to figure out what the bug might be. I am guessing that it's a bug in the `riskRegression` package but it's impossible to be sure. You could try the following things:

1. install the newest `riskRegression` package version from github
2. install the newest `adjustedCurves` package version from github
3. try to set `conf_int=FALSE`, does it still result in an error?
4. try it with only one covariate (or without covariates except the treatment) for either model, does it still throw the error? If no, you can try adding them one by one again to see what might cause the issue.

Maybe this helps?

**Comment by Madhav1812** [comment]
Hello,

Thank you for your inputs, there was probably some issue with my dataset, because using `conf_int=FALSE` seemed to work, although setting `conf_int=TRUE` seems to be taking a very long time. This is probably an issue on my side, so I can look into that. I did have a follow up question, if make a Cox regression object with the `Surv` object having `time` and `time2` inputs, is there a way to use the `adjustedCurves` function? It does give me an error at the moment, but I wasn't sure if there was a workaround.

Thank you so much for your help!

**Comment by RobinDenz1** [comment]
If it is a large dataset with many events it may be helpfull to use the `times` argument and supply it a grid of time points between `min(time) - max(time)`. By default, the survival probabilities are estimated at all points in time where an event occurred. This is overkill when many events happen close to each other though.

Regarding the `time2` argument: Unfortunately time-varying covariates are not supported in this package yet so there is no workaround I can give you.

**Comment by Madhav1812** [comment]
Right that makes sense, I will play around with some of the `times` arguments.

Thank you so much for your help!
