### ISSUE TITLE
How to get the p-value 

### ISSUE THREAD

**Issue by ltj-github** [RobinDenz1/adjustedCurves#25]
How do I get the p-value for the comparison between groups after using adjustedsurv?

**Comment by RobinDenz1** [comment]
That depends on what you want to test. If you want to test;

- differences in survival probabilities at some point in time: `adjusted_curve_diff()`
- differences in median survival time: `adjusted_surv_quantile()`
- differences in restricted mean survival times: `adjusted_rmst()`
- whether the integral of the difference between survival curves is 0 in some range: `adjusted_curve_test()`

**Comment by ltj-github** [comment]
Thanks for the reply, earlier I used the logarithmic rank test, which should be from start to end

**Comment by ltj-github** [comment]
Thank you for your response. Typically, I use the Log-rank test, which I think it should be from the beginning to the end of the event

**Comment by RobinDenz1** [comment]
There is no log-rank test equivalent test implemented in this package, because this has only been proposed for IPTW methods. If you use such a method, you should check out the `ipw.log.rank()` function in the `RISCA` R package. Otherwise you have to use one of the methods mentioned above.

**Comment by ltj-github** [comment]
Thank you for your guidance!

**Comment by RobinDenz1** [comment]
No problem!

**Comment by ltj-github** [comment]
As a beginner in statistics, many statistical problems often make me feel overwhelmed, and there is no one to help me answer them. I am truly grateful for your assistance.

**Comment by RobinDenz1** [comment]
I feel you. If you have further questions about the package don't hesitate to let me know.

**Comment by ltj-github** [comment]
You're so nice, thank you
