### ISSUE TITLE
Error when using adjustedsurv function with survreg object

### ISSUE THREAD

**Issue by swarupswaminathan** [RobinDenz1/adjustedCurves#27]
Hi all -- I am getting an error when trying to use a survreg object which contains an accelerated failure time (AFT) survival model. Any idea why this error may be thrown? Is adjustedCurves::adjustedsurv unable to handle survreg objects?

```
test_grouped_alt <- survreg(Surv(time_overall, sx) ~  age_firstvisit_c + 
                             gender + 
                             race_char +
                             group +
                             payer,
                           cluster=studyid,
                           data= as.data.frame(surv_df),
                           dist = 'lognormal')

survtest <- adjustedCurves::adjustedsurv(data = as.data.frame(surv_df), 
                            variable = "group",
                            ev_time = "time_overall",
                            event = "sx",
                            method = "direct",
                            outcome_model = test_grouped_alt,
                            cause = 1,
                            conf.int = FALSE)
```

Error noted:
`Error in value[[3L]](cond) : 
  The following error occured using the default S3 predict method: 'Error in eval(predvars, data, env): object 'age_firstvisit_c' not found
' Specify a valid 'predict_fun' or use a different model. See details.`

**Comment by RobinDenz1** [comment]
`survreg` objects are currently not directly supported. You may be able to use them anyways though, if you specify a valid `predict_fun`. How exactly this works is described in `?models_surv_direct`. If you are unable to do this you might want to use another model. For example, `flexsurvreg()` should work directly with the `adjustedsurv()` function and is quite similar to `survreg()`.

**Comment by swarupswaminathan** [comment]
Thank you. However, using flexsurvreg() to generate an analogous model seems to generate a different error with adjustedsurv:

`Error in `[.data.frame`(newdata, , term) : undefined columns selected`

**Comment by RobinDenz1** [comment]
Without a reproducible example it is impossible for me to tell you what the problem is. Please provide one.
My only guess without it would be that you should set the `data` object to be a `data.frame` outside of the function calls. E.g.
```R
surv_df <- as.data.frame(surv_df)
```
And then simply supply `surv_df` to both the model function and the `adjustedsurv()` function without calling `as.data.frame()` again.

**Comment by swarupswaminathan** [comment]
Actually I was using an identity() function in my original model which was causing issues. Resolved once I removed that. Thank you!

**Comment by RobinDenz1** [comment]
Alright, glad to hear it!

**Comment by swarupswaminathan** [comment]
A follow up question -- how can I find the time to a cumulative incidence percentage among the different groups in variable of interest from the adjustedsurv object? 

For example, I have generated a plot of the curve using cif = 1 to get adjusted cumulative incidences of the event, and I can graphically appreciate a difference in the time it takes to reach 10% incidence between the 3 groups of my variable of interest. How can I extract the precise time value that the 3 groups hit 10% incidence?

**Comment by RobinDenz1** [comment]
You can rerun the original `adjustedcif(()` call and change the `times` argument to obtain only the probabilities at certain points in time. Alternatively, you could also use the `update()` function directly.
