### ISSUE TITLE
Additional arguments not getting passed

### ISSUE THREAD

**Issue by asb2111** [RobinDenz1/adjustedCurves#28]
Hello, thank you for writing this amazing package!

I am trying to pass additional arguments to the WeightIt package when calling adjustedsurv and iptw_km, and it seems the additional arguments I'm passing aren't making it through. In particular, I am trying to set estimand = "ATT". I think the issue is that doCall is being passed with .ignoreUnusedArgs=TRUE (the default), which is causing the dots to be dropped from the call. When I make that change I am getting the expected results.

**Comment by RobinDenz1** [comment]
Thank you a lot for bringing this to my attention. This is indeed a bug and needs to be fixed. I am honestly suprised that this never turned up on any tests before.

**Comment by RobinDenz1** [comment]
The issue should be fixed on github. Will push this fix to CRAN soon.

**Comment by asb2111** [comment]
Wow, that was the fastest response and fix I’ve ever seen, thank you!
