### ISSUE TITLE
Is adjustedcif() suitable for weighted fine-gray model?

### ISSUE THREAD

**Issue by Ink-Mo** [RobinDenz1/adjustedCurves#29]
Hi, Robin,
Recently, I have tried to fit a weighted fine-gray model by arg of treatment_model=weights. but I think the weights are not adopted for analysis.

**Comment by RobinDenz1** [comment]
The `adjustedCurves` package allows you to estimate adjusted cause-specific cumulative incidence functions. You can use a Fine & Gray model for this purpose by using `method="direct"` in the `adjustedcif()` function. Alternatively, you can use weights directly to adjust the curves by using `method="iptw_pseudo` or `method="iptw"`. Using both at the same time is currently not supported.
