### ISSUE TITLE
Censoring model not passed on to cif_aiptw from surv_aiptw

### ISSUE THREAD

**Issue by jguski** [RobinDenz1/adjustedCurves#34]
Hi Robin,
Thanks for the great package, it's really helpful for my current research project. 
I noticed that there is a typo in [`method_aiptw.r`, line 74](https://github.com/RobinDenz1/adjustedCurves/blob/062ff659c78838a09bceb6b6564944d16ea276c6/R/method_aiptw.r#L74) (cencoring_model= instead of censoring_model=). As a result, the censoring model is never passed on to `cif_aiptw` and `riskRegression::ate`.

Best wishes
Jannis

**Comment by RobinDenz1** [comment]
Thank you very much for bringing this to my attention. This is indeed a typo. Wonder how that never turned up on any of the tests. Will be fixed on next commit!
