### ISSUE TITLE
force_bounds=TRUE has no effect on bootstrap results

### ISSUE THREAD

**Issue by jguski** [RobinDenz1/adjustedCurves#35]
Another thing I noticed is that (unlike the results saved in `adj`), the bootstrap results in `boot_adj` are never forced to lie between 0 and 1 even if `force_bounds=TRUE`.  I would expect this to be done somewhere around this line: https://github.com/RobinDenz1/adjustedCurves/blob/062ff659c78838a09bceb6b6564944d16ea276c6/R/adjustedsurv.r#L487

Best wishes
Jannis

**Comment by RobinDenz1** [comment]
Again, thank you for noticing this. This one is a little bit trickier though, because I am not sure whether to apply `force_bounds` (and `iso_reg` for that matter) to every bootstrap sample or only to the final one. Will have to think about that.
