### ISSUE TITLE
Change font size of axis label and ticks

### ISSUE THREAD

**Issue by JAMES-YI** [RobinDenz1/adjustedCurves#38]
Looks like the font size of the figure and risk table cannot be customized
- axis label font size
- axis tick font size
- legend font size

Also the range of axis limits cannot be changed
![deathKMCAdjusted11_Liver texture level2](https://github.com/user-attachments/assets/bf4d3eea-e856-4ce0-9751-0e37461f34f5)

**Comment by JAMES-YI** [comment]
Worked for the figure part. What about 
- If I want to show only the year from 0 to 5? currently the figure has too much white space
- if I want to also change the risk table font size? 

This what we currently can do

![deathKMCAdjusted11_LmS texture level7](https://github.com/user-attachments/assets/1b0d15e2-6ab3-45e7-a7a3-de0eb3d861de)

**Comment by JAMES-YI** [comment]
I followed the vignette to adjust the risk table formats, and it worked pretty well. Now another question is can we show only the horizontal axis from year 0 to year 5? 

![deathKMCAdjusted11_LmS texture level7](https://github.com/user-attachments/assets/ac2395c4-a8b0-4e50-9240-ce5e6cfa84b7)


This is what we can get now

**Comment by RobinDenz1** [comment]
Try setting `max_t` to 5, maybe this does what you're looking for. Other then that there are also some argument to change x-axis ticks which may potentially be used

**Comment by JAMES-YI** [comment]
Thanks. I'll give it a try. :)
