### ISSUE TITLE
adjusted_rmst() with WeightIt object

### ISSUE THREAD

**Issue by fedenichetti** [RobinDenz1/adjustedCurves#39]
Hi there, I am using the `adjusted_rmst()` function, and I want to provide the weights from an analysis I ran with the WeightIt package, with the following parameters:

```
w <- weightit(arm ~ x1 + x2 + x3,
              data = data,
              method = "glm", 
              estimand = "ATT",
              verbose = T, 
              focal = "a"
              )

adjsurv <- adjustedsurv(data=data,
                        variable="arm", 
                        ev_time="survival",
                        event="censoring_status",
                        method="iptw_km",
                        treatment_model=w$formula,
                        conf_int=TRUE, 
                        bootstrap = T, nboot = 1000
)

adjusted_rmst(adjsurv, to = tau_value, conf_int = TRUE, contrast = "ratio", 
                                  group_1 = "a", group_2 ="b")
```

My question is: what happens within the function when I provide the `treatment_model=w$formula` argument? Does it use the weights (based on my parameters) from my `w` object to adjust, or just takes the formula and uses another method? 
  
I cannot tell how much I appreciate your packages, I'll be citing! thanks!!

**Comment by fedenichetti** [comment]
Thanks Robin. I used the w$formula because when I directly provide the
w$weights it does not allow to bootstrap, which I need for the
asjusted_rmst() function to make comparisons.
Based on your answer, if I provide the formula to treatment _model, how is
the
weightit() function used under the hood? With ATT as I specified, or with
default parameters? With glm or other methods? Sorry to ask again.
Best, Fede

**Comment by RobinDenz1** [comment]
Ah I see. You need to pass the additional arguments of `weightit()` (such as `estimand` and `focal`) to the `adjustedsurv()` function as well in that case. So your call would be:
```R
adjsurv <- adjustedsurv(data=data,
                        variable="arm", 
                        ev_time="survival",
                        event="censoring_status",
                        method="iptw_km",
                        treatment_model=arm ~ x1 + x2 + x3,
                        conf_int=TRUE, 
                        bootstrap = T,
                        n_boot = 1000,
                        estimand = "ATT",
                        focal = "a",
                        weight_method = "glm" # (this is the only argument with a different name than used in weightit())
)

adjusted_rmst(adjsurv, to = tau_value, conf_int = TRUE, contrast = "ratio", 
                                  group_1 = "a", group_2 ="b")
```
The reason that just passing the weights does not work with bootstrapping is that to estimate standard errors correctly, all parts of the estimation process have to be repeated on the bootstrap sample (e.g. the weights also have to be estimated again and again). This works using the code I gave you, sorry for the oversight.

**Comment by fedenichetti** [comment]
All clear, thanks and congrats again! Best, Fede
