### ISSUE TITLE
incompatible with clustermq? 

### ISSUE THREAD

**Issue by craignvs** [RobinDenz1/adjustedCurves#40]
Hi Robin,

Thank you for your work on this package, providing a nice implementation covering all the mainstream methods and keeping up-to-date. I am trying to run a simulation with clustermq, however it seems to be stuck and also occasionally output `cannot allocate vector of size xxx` error message. Is there any know issue with clustermq, do you suggest using another parallel computation package for simulations?

```

library(clustermq)

simulation <- function(seeds){
  set.seed(seeds)
  
  # simulate some data as example
  sim_dat <- sim_confounded_surv(n=50, max_t=1.2)
  sim_dat$group <- as.factor(sim_dat$group)
  
  # estimate a cox-regression for the outcome
  cox_mod <- coxph(Surv(time, event) ~ x1 + x2 + x3 + x4 + x5 + x6 + group,
                   data=sim_dat, x=TRUE)
  
  # estimate a treatment assignment model
  glm_mod <- glm(group ~ x1 + x3 + x5 + x6, data=sim_dat, family="binomial")
  
  # use it to calculate adjusted survival curves
  adjsurv <- adjustedsurv(data=sim_dat,
                          variable="group",
                          ev_time="time",
                          event="event",
                          method="direct",
                          outcome_model=cox_mod,
                          treatment_model=glm_mod,
                          conf_int=F)
  
  adjusted_curve_diff(adjsurv, times=1, conf_int=F) %>% mutate(seed = seeds)
}

simulation(seeds = 1)

sims <- Q(simulation, seeds = 1:10, n_jobs = 10, pkgs = "adjustedCurves")
```

**Comment by RobinDenz1** [comment]
I cannot replicate this problem. Your code runs completely fine on my machine.  The error message "cannot allocate vector of size xxx" is usually thrown by the `ate()` function of the `riskRegression` package, which is used to estimate the survival curves when using `method="direct"` or `method="aiptw"`. This tends to happen sometimes with very large datasets and is being investigated by the `riskRegression` package maintainers. Note that setting `conf_int=FALSE` for large data may help.

**Comment by craignvs** [comment]
thank you for the quick reply! after some investigation I think it's due to the package was not installed on the cluster environment. Adding the library loading inside function resolved the problem.
