### ISSUE TITLE
Question after IPTW twang package

### ISSUE THREAD

**Issue by coconning** [RobinDenz1/adjustedCurves#5]
Hi, I am so happy to meet your good package.
But my data has weights in TWANG package like survey weights
Is this also applicable to adjustedsurv functions?

I want to use this weight directly to cumulative incidence plot. 
Unfortunately, my data is too heavy.....

hope you have a nice day. 
Sincerely, 
Coconning Kang

**Comment by RobinDenz1** [comment]
I am not completely sure what you are looking for, but in general it is definitly possible to use any kind of weights.

For example, if you want to create inverse probability of treatment weighted cumulative incidence functions and you have binary time-to-event data (no competing events), you could estimate the weights using the twang package and then use something like this:
```
adj <- adjustedsurv(data=data, variable="YOUR_VARIABLE", ev_time="YOUR_EVENT_TIME", event="YOUR_EVENT",
                               method="iptw_km", treatment_model=weights)
plot(adj, cif=TRUE)
```
If you could supply some reproducible code of what you did and what you want I could give you a better answer.

**Comment by coconning** [comment]
Thanks!!!!
I finally understand your package.
I hope this will work!!!

**Comment by RobinDenz1** [comment]
No problem. Please consider citing the package in your paper if you end up using it. I will close this issue as solved now.

**Comment by coconning** [comment]
Yeah!!! I will !
