### ISSUE TITLE
ATE vs ATT estimands?

### ISSUE THREAD

**Issue by daniostr** [RobinDenz1/adjustedCurves#8]
Hi,

Are the estimands ATE or ATT? 
Thank you for the great package!

**Comment by RobinDenz1** [comment]
Thank you!

All estimands in this package can be considered ATE estimands. The main target estimand is defined in rigorous detail in the associated article: https://onlinelibrary.wiley.com/doi/full/10.1002/sim.9681

Hope this helps!

**Comment by daniostr** [comment]
How can it be modified to estimate the ATT?
Can I provide the weights for the analysis?

**Comment by RobinDenz1** [comment]
You can obtain ATT estimates using inverse probability of treatment weighting (methods `iptw_km`, `iptw_cox`, `iptw_pseudo`) by simply supplying ATT based weights to the `treatment_model` argument directly. The syntax to supply weights directly is described in the relevant documentation pages.

It would be more difficult to do with other methods though

**Comment by daniostr** [comment]
Thank you so much, Robin.
